<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Basics</RootNamespace>
    <AssemblyName>Basics</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Sampling/Sampling.fsi" />
    <Compile Include="Sampling/Sampling.fs" />
    <Compile Include="Core/Vector.fs" />
    <Compile Include="Core/Colour.fs" />
    <Compile Include="Core/Point.fs" />
    <Compile Include="Core/Ray.fs" />
    <Compile Include="Core/BBox.fs" />
    <Compile Include="Core/Foundation.fs" />
    <Compile Include="PathTracing/Bsdf.fs" />
    <Compile Include="PathTracing/Surface.fs" />
    <Compile Include="Materials/Materials.fs" />
    <Compile Include="PathTracing/MaterialAdapter.fs" />
    <Compile Include="Materials/Textures.fsi" />
    <Compile Include="Materials/Textures.fs" />
    <Compile Include="Transformation/Transformation.fsi" />
    <Compile Include="Transformation/Transformation.fs" />
    <Compile Include="Shapes/Shapes.fs" />
    <Compile Include="Shapes/CSG.fs" />
    <Compile Include="Shapes/BaseShape.fs" />
    <Compile Include="Lights/GlobalLight.fs" />
    <Compile Include="Lights/BasicLight.fs" />
    <Compile Include="Lights/AreaLight.fs" />
    <Compile Include="Acceleration/KDTree.fs" />
    <Compile Include="Acceleration/BVH.fs" />
    <Compile Include="Acceleration/RegularGrids.fs" />
    <Compile Include="Acceleration/FlatBVH.fs" />
    <Compile Include="Acceleration/Acceleration.fs" />
    <Compile Include="Camera/Camera.fs" />
    <Compile Include="Camera/PinholeCamera.fs" />
    <Compile Include="Camera/ThinLensCamera.fs" />
    <Compile Include="TriangleMesh/PLYParser.fs" />
    <Compile Include="TriangleMesh/TriangleMesh.fs" />
    <Compile Include="ImplicitSurfaces/ExprParse.fsi" />
    <Compile Include="ImplicitSurfaces/ExprParse.fs" />
    <Compile Include="ImplicitSurfaces/ExprToPoly.fsi" />
    <Compile Include="ImplicitSurfaces/ExprToPoly.fs" />
    <Compile Include="ImplicitSurfaces/PolyToUnipoly.fsi" />
    <Compile Include="ImplicitSurfaces/PolyToUnipoly.fs" />
    <Compile Include="ImplicitSurfaces/ImplicitSurfaces.fsi" />
    <Compile Include="ImplicitSurfaces/ImplicitSurfaces.fs" />
    <Compile Include="Scene.fs" />
    <Compile Include="ClassicIntegrator.fs" />
    <Compile Include="PathTracing/Denoiser.fs" />
    <Compile Include="PathTracing/PathIntegrator.fs" />
    <Compile Include="Render.fs" />
    <Compile Include="API/API.fsi" />
    <Compile Include="API/API.fs" />
    <Compile Include="AssemblyInfo.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FParsec" Version="1.1.1" />
    <ProjectReference Include="../RayTracer.ImageIO/RayTracer.ImageIO.fsproj" />
  </ItemGroup>
</Project>
