// Demonstrates authoring a scene from a description rather than a downloaded
// model: every mesh here is generated by scripts/meshkit.fsx.
//
// The description: a still life on a stone plinth - a turned vase, a glass
// sphere, a polished metal sphere, a brass torus and a scattering of small
// spheres, on a wide floor, lit by a soft key light and sky.
//
// Usage: dotnet fsi scripts/make-demo-scene.fsx

#load "meshkit.fsx"
#r "../RayTracer/bin/Release/net10.0/Basics.dll"
#load "../SceneFormat/SceneFormat.fs"

open System
open System.IO
open Meshkit
open Tracer.SceneFormat

let root = Path.GetFullPath(Path.Combine(__SOURCE_DIRECTORY__, ".."))
let meshDir = Path.Combine(root, "artifacts/scene-assets/demo")

printfn "generating meshes:"

// A turned vase: profile is (radius, height) pairs revolved about +Y.
let vaseProfile =
    [| 0.00, 0.00; 0.42, 0.00; 0.44, 0.06; 0.30, 0.16; 0.26, 0.30
       0.34, 0.52; 0.46, 0.80; 0.50, 1.05; 0.44, 1.28; 0.30, 1.44
       0.27, 1.52; 0.32, 1.60; 0.34, 1.66; 0.30, 1.68; 0.00, 1.68 |]

let write name mesh = Mesh.writePly (Path.Combine(meshDir, name + ".ply")) mesh; name

let meshNames =
    [ write "floor" (Mesh.plane 2 |> Mesh.scaleUniform 400.)
      write "plinth" (Mesh.box () |> Mesh.scaleXyz 3.4 0.7 3.4 |> Mesh.translate 0. 0.35 0.)
      write "vase" (Mesh.lathe 96 vaseProfile |> Mesh.scaleUniform 1.5 |> Mesh.translate 0. 0.7 0.)
      write "glassball" (Mesh.sphere 96 48 |> Mesh.scaleUniform 0.62 |> Mesh.translate -1.35 1.32 0.55)
      write "metalball" (Mesh.sphere 96 48 |> Mesh.scaleUniform 0.52 |> Mesh.translate 1.35 1.22 -0.35)
      write "ring" (Mesh.torus 48 96 0.26 |> Mesh.scaleUniform 0.72
                    |> Mesh.rotateX 1.25 |> Mesh.translate 1.15 1.05 0.95)
      write "pebbles"
            ([ -2.6, 0.22, 1.9, 0.30; 2.9, 0.20, 1.4, 0.27; -3.1, 0.17, -1.2, 0.23
               2.4, 0.24, -2.3, 0.33; -1.6, 0.15, 2.9, 0.21; 3.4, 0.16, -0.4, 0.22 ]
             |> List.map (fun (x, y, z, r) -> Mesh.sphere 40 20 |> Mesh.scaleUniform r |> Mesh.translate x y z)
             |> Mesh.merge) ]

let colour r g b : float array = [| r; g; b |]
let identity : float array = [| 1.;0.;0.;0.; 0.;1.;0.;0.; 0.;0.;1.;0.; 0.;0.;0.;1. |]

let material id kind col reflection ambient diffuse specular exponent reflectivity gloss ior =
    { Id = id; Kind = kind; Colour = col
      AmbientColour = null; SpecularColour = null; ReflectionColour = reflection
      Ambient = ambient; Diffuse = diffuse; Specular = specular; Exponent = exponent
      Reflectivity = reflectivity; GlossExponent = gloss; Ior = ior
      Filter = colour 1. 1. 1.; Emission = 0.; Texture = "" }

let materials =
    [| material "floor" MaterialKind.Matte (colour 0.30 0.30 0.33) null 0. 0.9 0. 0 0. 0 1.5
       material "stone" MaterialKind.Phong (colour 0.55 0.53 0.49) null 0. 0.85 0.15 22 0. 0 1.5
       // Glazed ceramic: a coloured body under a smooth clear coat.
       material "glaze" MaterialKind.Glossy (colour 0.10 0.32 0.46) (colour 0.9 0.95 1.0) 0. 0.7 0.5 220 0.16 220 1.5
       material "glass" MaterialKind.Glass (colour 0.96 0.99 0.97) null 0. 0.1 0.4 260 0.1 0 1.52
       material "steel" MaterialKind.Glossy (colour 0.62 0.65 0.70) (colour 0.78 0.81 0.86) 0. 0.35 0.55 320 0.80 320 1.5
       material "brass" MaterialKind.Glossy (colour 0.88 0.66 0.26) (colour 0.95 0.76 0.36) 0. 0.5 0.5 140 0.68 140 1.5
       material "slate" MaterialKind.Matte (colour 0.32 0.31 0.30) null 0. 0.85 0. 0 0. 0 1.5 |]

let assign =
    dict [ "floor", "floor"; "plinth", "stone"; "vase", "glaze"
           "glassball", "glass"; "metalball", "steel"; "ring", "brass"; "pebbles", "slate" ]

let scene =
    { SchemaVersion = 1
      Id = "demo-still-life"
      Title = "Still life - geometry authored procedurally"
      Description =
        "Every mesh is generated by scripts/meshkit.fsx rather than downloaded: a lathed vase, boxes, "
        + "UV spheres and a torus. Original geometry, GPL-2.0-only alongside the rest of the repository."
      Camera =
        { Position = [| 4.9; 3.05; 6.6 |]; Target = [| 0.; 1.35; 0. |]; Up = [| 0.; 1.; 0. |]
          ViewDistance = 1.; ViewWidth = 2. * tan 0.36; ViewHeight = 2. * tan 0.36 * 0.625
          LensRadius = 0.; FocusDistance = 8.7 }
      AmbientColour = colour 0.5 0.55 0.65
      AmbientIntensity = 0.0
      MaxBounces = 10
      Materials = materials
      Meshes = meshNames |> List.map (fun n ->
          { Id = n; Path = "../../artifacts/scene-assets/demo/" + n + ".ply"
            Smooth = (n <> "plinth" && n <> "floor")
            Closed = (n = "glassball") }) |> List.toArray
      Objects = meshNames |> List.map (fun n ->
          { Id = n; Mesh = n; Material = assign.[n]; Transform = identity }) |> List.toArray
      Lights =
        [| // A large, close rectangle gives soft shadows; a small distant one
           // would give the hard-edged look of a point light.
           { Id = "key"; Kind = LightKind.Rectangle; Position = [| -3.4; 6.2; 4.2 |]
             Direction = [| 0.42; -1.; -0.42 |]; Colour = colour 1.0 0.96 0.90; Intensity = 26.0; Size = [| 4.6; 4.6 |] }
           { Id = "rim"; Kind = LightKind.Rectangle; Position = [| 5.0; 4.0; -4.6 |]
             Direction = [| -0.5; -0.62; 1. |]; Colour = colour 0.72 0.82 1.0; Intensity = 10.0; Size = [| 3.0; 3.0 |] }
           { Id = "sky"; Kind = LightKind.Environment; Position = [| 0.; 0.; 0. |]
             Direction = [| 0.; 1.; 0. |]; Colour = colour 0.40 0.50 0.68; Intensity = 0.55; Size = [| 1000000.; 1000000. |] } |]
      Subjects = meshNames |> List.filter (fun n -> n <> "floor") |> List.toArray }

let scenePath = Path.Combine(root, "benchmarks/scenes/demo-still-life.json")
SceneFiles.save scenePath scene
printfn ""
printfn "wrote %s" scenePath
